name: Daily Update

on:
  schedule:
    - cron: '0 5 * * *'  # 每天午夜5点触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update file
      run: |
        echo "Updating file content" >> yourfile.txt  # 示例：向文件添加内容
        git config --local user.email "jiangtaody@gmail.com"
        git config --local user.name "jiangtaody"
        git add yourfile.txt
        git commit -m "Daily update"
        git push origin main  # 推送到GitHub
